# Please see SoftRelTools/HOWTO-GNUmakefile for documentation
# $Id$
#################################################################
#++ library products				[build it with 'lib']

LIBREMOVEFILES := 
LIBTMPLFILES := 
LIBDDLORDERED :=

#################################################################
#++ extra binary products	[not in production, build it with extrabin]

EXTRABINS :=

$(addprefix $(bindir),$(EXTRABINS)): $(bindir)% : %.o

#################################################################
#++ binary products				[build it with 'bin']

BINS :=
BINCCFILES := $(BINS:=.cc) 

#++ Binary rules		 [in production, build it with 'bin']
$(addprefix $(bindir),$(BINS)): $(bindir)% : %.o

#++ shell script products.. 			[build it with 'bin']
BINSCRIPTS :=	FjrCheckJob

#################################################################
#++ regression test scripts			[build it with 'test']

SUBDIRS = src
#################################################################
#++ include standard makefile from SoftRelTools.
include SoftRelTools/standard.mk


