# Please see SoftRelTools/HOWTO-GNUmakefile for documentation
# $Id$
#################################################################
#++ library products				[build it with 'lib']

LIBREMOVEFILES := IfdNoCompileTest.cc IfdSimpleProxyDictSpeedTest.cc
LIBTMPLFILES := IfdDataProxyTemplate.cc Ifd.cc AbsArgCast.cc \
	AbsArgVal.cc IfdAliasProxy.cc IfdDataProxy.cc IfdDataProxyUnowned.cc \
	IfdHepAListProxyTemplate.cc IfdHepAListProxy.cc \
	IfdTypeKey.cc
LIBDDLORDERED := 

#################################################################
#++ extra binary products	[not in production, build it with extrabin]

EXTRABINS := 

#################################################################
#++ binary products				[build it with 'bin']

BINS := 
BINCCFILES := $(BINS:=.cc) 

#++ Binary rules		 [in production, build it with 'bin']

$(addprefix $(bindir),$(BINS)): $(bindir)% : %.o 

#++ shell script products.. 			[build it with 'bin']
BINSCRIPTS := 

#################################################################
#++ regression test scripts			[build it with 'test']

SUBDIRS = src test
#################################################################
#++ include standard makefile from SoftRelTools.
include SoftRelTools/standard.mk
