# Please see SoftRelTools/HOWTO-GNUmakefile for documentation
# $Id$
#################################################################
#++ library products				[build it with 'lib']

LIBREMOVEFILES := 
LIBTMPLFILES := 
LIBDDLORDERED := 

NOFWKMAIN := yes

#################################################################
#++ extra binary products	[not in production, build it with extrabin]

EXTRABINS := 

#################################################################
#++ binary products				[build it with 'bin']

BINS := TrkExchangeDataTest TrkHelixDataTest TrkDifPieceTrajTest TrkHotListDataTest
BINCCFILES := TrkExchangeDataTest.cc TrkHelixDataTest.cc TrkDifPieceTrajTest.cc TrkHotListDataTest.cc

#++ Binary rules		 [in production, build it with 'bin']
$(addprefix $(bindir),$(BINS)): $(bindir)% : %.o

#++ shell script products.. 			[build it with 'bin']
BINSCRIPTS := 

#################################################################
#++ regression test scripts			[build it with 'test']

#################################################################
#++ include standard makefile from SoftRelTools.
include SoftRelTools/standard.mk
