//  PacDKChainInfo.cc   03 November  2008
//   revised 23 November 2008
//
// Objects in this class will cache information
// related to how a track decays.
// It is anticipated that the information will
// be generated by a PacDKPointGenerator using
// the set[...] methods or the generateDecay method.
//
//
//  Mike Sokoloff
//

#include "BaBar/BaBar.hh"
#include "PacSim/PacDKChainInfo.hh"

#include <vector>
using namespace std;

  // the simplest constructor 
PacDKChainInfo::PacDKChainInfo() :
_decayChainGenerated(false),_thePacDKPointInfo(0),_theParent(0){
}

PacDKChainInfo::PacDKChainInfo(const PacDKChainInfo& other)
 : _decayChainGenerated(other._decayChainGenerated), 
   _thePacDKPointInfo(other._thePacDKPointInfo),
   _theDaughters(other._theDaughters) ,_theParent(other._theParent){
}

void
PacDKChainInfo::decayChainInit(const EvtParticle* parent) {
  _theDaughters.reserve(4);
  _decayChainGenerated = true;
  _theParent = parent;
}

void 
PacDKChainInfo::addDaughter(const EvtParticle* aDaughter) {
  _theDaughters.push_back(aDaughter);
}

PacDKChainInfo&
PacDKChainInfo::operator = (const PacDKChainInfo& other) {
 if(this != &other)  {
   _thePacDKPointInfo=other._thePacDKPointInfo;
   _decayChainGenerated=other._decayChainGenerated;
   _theDaughters=other._theDaughters;
   _theParent = other._theParent;
 }
 return *this;
}


// a basic destructor
PacDKChainInfo::~PacDKChainInfo(){
// daughters and parent EvtParticle are owned OUTSIDE this class
}
