# Please see SoftRelTools/HOWTO-GNUmakefile for documentation
# $Id$
#################################################################
#++ library products				[build it with 'lib']

LIBREMOVEFILES := 
LIBTMPLFILES := ComPrintOnDelete.cc BbrRefCountedPointer.cc \
	ComTemplatedBitMap.cc BbrCounter.cc
LIBDDLORDERED := 

#################################################################
#++ extra binary products	[not in production, build it with extrabin]

EXTRABINS :=

#################################################################
#++ binary products				[build it with 'bin']

BINS := 
BINCCFILES := $(BINS:=.cc)

#++ Binary rules		 [in production, build it with 'bin']

$(addprefix $(bindir),$(BINS)): $(bindir)% : %.o

#++ shell script products.. 			[build it with 'bin']
BINSCRIPTS := 

#################################################################
#++ regression test scripts			[build it with 'test']

$(testdir)RefCnt.T $(testdir)basic.T $(testdir)timer.T : test$(PACKAGE)
$(testdir)testBbrRefCountedPointer.T : testBbrRefCountedPointer
$(testdir)testComPackBoolsIntoOctet.T : testComPackBoolsIntoOctet
$(testdir)testBbrBitVector.T : testBbrBitVector
$(testdir)testComExtendedArgValues.T : testComExtendedArgValues
$(testdir)testComExtendedSyntaxParser.T : testComExtendedSyntaxParser

SUBDIRS = src test
#################################################################
#++ include standard makefile from SoftRelTools.
include SoftRelTools/standard.mk
